### ISSUE TITLE
Inverse solution result selection

### ISSUE THREAD

**Issue by demodemode** [lakehanne/awesome-screw-theory#1]
Excuse me ,I want to ask how do you select the best set of 8 inverse solutions or the set of solutions that the positive solution put in the first place？Hoping to your reply！

**Comment by robotsorcerer** [comment]
I cannot make sense of this question. Closing it.

**Comment by demodemode** [comment]
Thanks your reply! My question is following: In&nbsp;your&nbsp;inverse&nbsp;solution&nbsp;program,&nbsp;you&nbsp;first&nbsp;randomly&nbsp;select&nbsp;a&nbsp;set&nbsp;of&nbsp;joint&nbsp;angles&nbsp;into&nbsp;the&nbsp;forward&nbsp;kinematics,&nbsp;and&nbsp;then&nbsp;put&nbsp;the&nbsp;obtained&nbsp;matrix&nbsp;into&nbsp;the&nbsp;inverse&nbsp;kinematics,&nbsp;and&nbsp;finally&nbsp;get&nbsp;8&nbsp;sets&nbsp;of&nbsp;solutions.&nbsp;So&nbsp;how&nbsp;do&nbsp;I&nbsp;directly&nbsp;choose&nbsp;the&nbsp;set&nbsp;of&nbsp;joint&nbsp;angles&nbsp;that&nbsp;I&nbsp;originally&nbsp;chose&nbsp;from&nbsp;the&nbsp;8&nbsp;sets&nbsp;of&nbsp;inverse&nbsp;solutions? Hoping your reply! Thanks a lot!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "robotsorcerer/awesome-screw-theory"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 晚上6:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [robotsorcerer/awesome-screw-theory] Inverse solution result selection (Issue #1)





 
Closed #1 as not planned.
